apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-configmap
data:
  appsettings.json: |-
    {
      "DB" : "10.22.22.45",
      "Logging": {
        "LogLevel": {
          "Default": "Error",
          "System": "Error",
          "Microsoft": "Error"
        }
      },
      "AppConfiguration": {
        "DatabaseHost": "localhost",
        "ThirdPartyAPIBaseURL" :  "https://local.somewhere.com/"
      }
    }